name: Build and Deploy
on:
  push:
    branches:
      - master
        - 
jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    - name: Deploy frontend
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "frontend/public/*"
        target: "/data/www/chess"
